/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"

float *
sum_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	 printf("Proceso de suma activo");
	 result = argp->num1+argp->num2;
	 printf("Su solicitud: SUMA %f + %f\n",argp->num1,argp->num2);
	 printf("El resultado es: %f\n",result);

	return &result;
}

float *
res_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	 printf("Proceso de Resta activo");
	 result = argp->num1-argp->num2;
	 printf("Su solicitud: RESTA %f + %f\n",argp->num1,argp->num2);
	 printf("El resultado es: %f\n",result);

	return &result;
}

float *
mul_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	 printf("Proceso de Multiplicacion activo");
	 result = argp->num1*argp->num2;
	 printf("Su solicitud: MULTIPLICACION %f + %f\n",argp->num1,argp->num2);
	 printf("El resultado es: %f\n",result);

	return &result;
}

float *
div_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	 printf("Proceso de division activo");
	 result = argp->num1/argp->num2;
	 printf("Su solicitud: DIVISION %f + %f\n",argp->num1,argp->num2);
	 printf("El resultado es: %f\n",result);

	return &result;
}
