/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"


float calculadora_prog_1(char *host,float n1,float n2,char opr,CLIENT *clnt)
{
	CLIENT *clnt;
	float  *result_1;
	inputs  sum_1_arg;
	float  *result_2;
	inputs  res_1_arg;
	float  *result_3;
	inputs  mul_1_arg;
	float  *result_4;
	inputs  div_1_arg;

if(opr=='+'){
sum_1_arg.num1=n1;
sum_1_arg.num2=n2;
sum_1_arg.operador=opr;
result_1 = sum_1(&sum_1_arg, clnt);
if(result_1 == (float *)NULL){
clnt_perror (clnt, "call failed");
}
return * result_1;
}
else if(opr=='-'){
res_1_arg.num1=n1;
res_1_arg.num2=n2;
res_1_arg.operador=opr;
result_2 = res_1(&res_1_arg, clnt);
if(result_2 == (float *)NULL){
clnt_perror (clnt, "call failed");
}
return * result_2;
}
else if(opr=='*'){
mul_1_arg.num1=n1;
mul_1_arg.num2=n2;
mul_1_arg.operador=opr;
result_3 = mul_1(&mul_1_arg, clnt);
if(result_3 == (float *)NULL){
clnt_perror (clnt, "call failed");
}
return * result_3;
}
else if(opr=='/'){
div_1_arg.num1=n1;
div_1_arg.num2=n2;
div_1_arg.operador=opr;
if(n2==0)
{ 
printf("La division de cero no es valida.\n");
exit(0);
}else{
result_4 = div_1(&sum_1_arg, clnt);
if(result_4 == (float *)NULL){
clnt_perror (clnt, "call failed");
}
return * result_4;
}
}
}


#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sum_1(&sum_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = res_1(&res_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mul_1(&mul_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int arg, char *argv[])
{
char *host;
float a,b;
char op;
CLIENT *clnt;
if(argc < 2) 
{
printf("Uso: %s server_host\n",argv[0]);
exit(1);
}
printf("**Calculadora RPC**\n");
printf("(+) Suma\n");
printf("(-) Resta\n");
printf("(*) Multiplicacion\n");
printf("(/) Division\n");

printf("Ingresa el 1er numero\n");
scanf("%f",&a);

printf("Ingresa el 2do numero\n");
scanf("%f",&b);

printf("Ingresa el operador\n");
scanf("%s",&op);

host=argv[1];
clnt = clnt_create(host, CALCULADORA_PROG, CALCULADORA_VER, "udp");

if (clnt==NULL){
clnt_pcreateerror (host);
exit(1);
}

printf("El resultado es: = %f\n",calculadora_prog_1(host,a,b,op,clnt));
clnt_destroy(clnt);
exit(0);
}

